/**
 * ThyStreet
 * Thy Street APIs are completely RESTful and all our responses are returned in JSON.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@thystreet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeviceTokenDto model module.
 * @module model/DeviceTokenDto
 * @version 0.0.1
 */
class DeviceTokenDto {
    /**
     * Constructs a new <code>DeviceTokenDto</code>.
     * @alias module:model/DeviceTokenDto
     * @param deviceId {String} Device ID
     * @param token {Boolean} Set device token 
     */
    constructor(deviceId, token) { 
        
        DeviceTokenDto.initialize(this, deviceId, token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deviceId, token) { 
        obj['deviceId'] = deviceId;
        obj['token'] = token;
    }

    /**
     * Constructs a <code>DeviceTokenDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceTokenDto} obj Optional instance to populate.
     * @return {module:model/DeviceTokenDto} The populated <code>DeviceTokenDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceTokenDto();

            if (data.hasOwnProperty('deviceId')) {
                obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Device ID
 * @member {String} deviceId
 */
DeviceTokenDto.prototype['deviceId'] = undefined;

/**
 * Set device token 
 * @member {Boolean} token
 */
DeviceTokenDto.prototype['token'] = undefined;






export default DeviceTokenDto;

