/**
 * ThyStreet
 * Thy Street APIs are completely RESTful and all our responses are returned in JSON.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@thystreet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeviceStatusDto model module.
 * @module model/DeviceStatusDto
 * @version 0.0.1
 */
class DeviceStatusDto {
    /**
     * Constructs a new <code>DeviceStatusDto</code>.
     * @alias module:model/DeviceStatusDto
     * @param available {Boolean} Set current device availablity
     * @param deviceId {String} Device ID
     */
    constructor(available, deviceId) { 
        
        DeviceStatusDto.initialize(this, available, deviceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, available, deviceId) { 
        obj['available'] = available;
        obj['deviceId'] = deviceId;
    }

    /**
     * Constructs a <code>DeviceStatusDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeviceStatusDto} obj Optional instance to populate.
     * @return {module:model/DeviceStatusDto} The populated <code>DeviceStatusDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeviceStatusDto();

            if (data.hasOwnProperty('available')) {
                obj['available'] = ApiClient.convertToType(data['available'], 'Boolean');
            }
            if (data.hasOwnProperty('deviceId')) {
                obj['deviceId'] = ApiClient.convertToType(data['deviceId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Set current device availablity
 * @member {Boolean} available
 */
DeviceStatusDto.prototype['available'] = undefined;

/**
 * Device ID
 * @member {String} deviceId
 */
DeviceStatusDto.prototype['deviceId'] = undefined;






export default DeviceStatusDto;

